### ISSUE TITLE
How does this look like?

### ISSUE THREAD

**Issue by danse** [league/yesod-crud#4]
I would like to see some screenshots of a sample CRUD generated with this package

**Comment by league** [comment]
This is the main screen of a little user administration facility in the example site provided. However, the big caveat is that virtually all of the styling is provided by Lucius code in the example site definition, rather than by the library on its own. The example site also incorporates bootstrap.

**Comment by danse** [comment]
Great, thanks :+1:

**Comment by danse** [comment]
By the way, if you don't want to maintain bothersome Cascading Style Sheets, a good idea could be to change the markup in order to match the Bootstrap style. That way, you would get high-quality style and a lot of themes for free!
